language: java

jdk:
  - oraclejdk8

before_install:
  - nvm install 4.4

env:
  - BUILD_CMD="mvn -f catalog-spring-boot install"
  - BUILD_CMD="mvn -f gateway-vertx install"
  - BUILD_CMD="mvn -f inventory-wildfly-swarm install"
  - BUILD_CMD="npm install --prefix web-nodesjs"
  - BUILD_CMD="mvn -f solutions/all/catalog-spring-boot install"
  - BUILD_CMD="mvn -f solutions/all/gateway-vertx install"
  - BUILD_CMD="mvn -f solutions/all/inventory-wildfly-swarm install"

script:
  - $BUILD_CMD